### PR TITLE
fix absolute path

### PR DESCRIPTION
**Pull request by nim65s**
to fix CI.

If the model is different in ferrum, something a bit more clever might need to be used

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
I cannot merge this...

**Comment by nim65s** [comment]
what about now ?

**Comment by NahuelVilla** [comment]
Still not able to merge :/

**Comment by nim65s** [comment]
@NahuelVilla : you might still need to accept the invite: https://github.com/Gepetto/aig/invitations

**Comment by NahuelVilla** [comment]
Yes, sorry,

**Pull request merged**
