### PR TITLE
fix the computation of the centroidal dynamics and the test against t…

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
This PR fixes:

- the computation of the dynamcis using Pioncchio and a unit-test on a static posture.
- the check on the creation of settings using a robot name
- rename the private method "void configurateLegs();" into " void configureLegs();"
- add some getters on the CoM and its derivatives

### CODE REVIEW

**Comment by MaximilienNaveau** [comment]
@nim65s I have a weird behavior, I have install pre-commit on my laptop and on this package and it succeed upon commit, but not here... I wonder why.

**Comment by MaximilienNaveau** [comment]
Up we should merge this!!! has anyone took the time to check this?

**Review by nim65s — APPROVED** [review]

**Comment by NahuelVilla** [comment]
I had a look. 

You changed the computation of the angular momentum to not use the RNEA, but the RNEA is still used for the computation of the non-linearities. It would be better if we also remove the RNEA from the computation of n.

**Comment by NahuelVilla** [comment]
It is also important because the angular momentum is taken from the RNEA for the computation of n, and you mentioned that they had different values.

I can fix that later. Do not worry.

**Comment by pFernbach** [comment]
Good for me, thanks

**Comment by MaximilienNaveau** [comment]
This was not to be merge until Nahuel fix the method.
@NahuelVilla Can you please create another branch and merge request to fix back this function?

**Comment by NahuelVilla** [comment]
Yes, no problem. Actually the fixing is quite independent, and it should work right now anyway. 

So, it is ok, I will push the correction in another branch. (I guess tomorrow)

**Pull request merged**
